name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
        
    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r21e
        
    - name: Setup NINJA
      uses: seanmiddleditch/gha-setup-ninja@v3
      
    - name: Build native FFmpeg and BoringSSL dependencies
      run: |
        cd TMessagesProj/jni
        export NDK=${{ steps.setup-ndk.outputs.ndk-path }}
        export NINJA_PATH=${GITHUB_WORKSPACE}/ninja-build
        ./build_libvpx_clang.sh
        ./build_ffmpeg_clang.sh
        ./patch_ffmpeg.sh
        ./patch_boringssl.sh
        ./build_boringssl.sh
        
    - name: Create APIKey
      run: |
        echo APP_ID=${{ secrets.API_ID }} > API_KEYS
        echo APP_HASH=${{ secrets.API_HASH }} >> API_KEYS
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build
        ./gradlew assembleAfatRelease
