name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build Android APK

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
  
    - name: Android NDK toolchain Setup
      id: setup-ndk
      
        
    - name: Setup NINJA
      uses: seanmiddleditch/gha-setup-ninja@v3
      
    - name: Build native FFmpeg and BoringSSL dependencies
      run: |
        cd TMessagesProj/jni
        export NDK=${GITHUB_WORKSPACE}/ndk-toolchain
        export NINJA_PATH=${GITHUB_WORKSPACE}/ninja-build
        ./build_libvpx_clang.sh arm64
        ./build_ffmpeg_clang.sh arm64
        ./patch_ffmpeg.sh arm64
        ./patch_boringssl.sh arm64
        ./build_boringssl.sh arm64
        
    - name: Create APIKey
      run: |
        echo APP_ID=${{ secrets.API_ID }} > API_KEYS
        echo APP_HASH=${{ secrets.API_HASH }} >> API_KEYS
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build
        ./gradlew assembleAfatRelease
