name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Buidl APK
    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
  
    - name: Setup Android NDK toolchain
      id: setup-ndk
      uses: nttld/setup-ndk@v1.0.6
      with:
        ndk-version: r21e
        
    - name: Setup NINJA
      uses: seanmiddleditch/gha-setup-ninja@v3
      
    - name: Build native FFmpeg and BoringSSL dependencies
      env:
        NDK: ${{ steps.setup-ndk.outputs.ndk-path }}
        NINJA_PATH: ${{ github.workspace }}/ninja-build/ninja
      run: |
        cd TMessagesProj/jni
        ./build_libvpx_clang.sh arm arm64
        ./build_ffmpeg_clang.sh arm arm64
        ./patch_ffmpeg.sh arm arm64
        ./patch_boringssl.sh arm arm64
        ./build_boringssl.sh arm arm64
      
    - name: Create APIKey
      run: |
        echo APP_ID=${{ secrets.API_ID }} > API_KEYS
        echo APP_HASH=${{ secrets.API_HASH }} >> API_KEYS
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew assembleAfatRelease
