name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Setup JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
  
    - name: Android NDK toolchain Setup
      # You may pin to the exact commit or the version.
      # uses: ravinderjangra/android-ndk-toolchain-setup@88bfbd8e61af597832637fb9d2f81a7cc68d1331
      uses: ravinderjangra/android-ndk-toolchain-setup@0.2
      with:
        api: 21
        arch: 'arm64'
        install-location: ${GITHUB_WORKSPACE}/ndk-toolchain
        
    - name: Setup NINJA
      uses: seanmiddleditch/gha-setup-ninja@v3
      
    - name: Build native FFmpeg and BoringSSL dependencies
      run: |
        cd TMessagesProj/jni
        export NDK=${GITHUB_WORKSPACE}/ndk-toolchain
        export NINJA_PATH=${GITHUB_WORKSPACE}/ninja-build
        ./build_libvpx_clang.sh
        ./build_ffmpeg_clang.sh
        ./patch_ffmpeg.sh
        ./patch_boringssl.sh
        ./build_boringssl.sh
        
    - name: Create APIKey
      run: |
        echo APP_ID=${{ secrets.API_ID }} > API_KEYS
        echo APP_HASH=${{ secrets.API_HASH }} >> API_KEYS
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: |
        ./gradlew build
        ./gradlew assembleAfatRelease
